services:
  app:
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/app/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/app/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    networks:
      - laravel-network
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-webserver
    restart: unless-stopped
    ports:
      - "89:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}-redis
    ports:
      - "127.0.0.1:6389:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
